name: msg on first issue

on: [issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for creating this issue! Looks like it's your first one. Thanks for supporting Edu with all your suggestions, bug reports and improvements!"
